### ISSUE TITLE
fix timezone check in scrappy app

### ISSUE THREAD

**Issue by JosiasAurel** [hackclub/scrappy#600]
The scrappy app occasionally crashes with the following logs - apparently failing a timezone check
```
2024-05-17T21:01:25.807152+00:00 heroku[router]: at=info method=GET path="/api/streakResetter?date_day=17&date_month=5&date_year=2024&day_of_week=4&id=2024-05-17T14%3A01%3A25-07%3A00&next_occurrence=2024-05-17T22%3A00%3A00Z&pretty_date=May+17%2C+2024&pretty_day_of_week=Friday&pretty_next_occurrence=May+17%2C+2024+3%3A00%3A00+PM+-07%3A00&pretty_time=02%3A01%3A25+PM&time_hour=2&time_minute=1&time_second=25&week_of_year=20" host=scrappy.hackclub.com request_id=4180e33e-99ec-4a47-bc06-732108c6342a fwd="3.220.115.188" dyno=web.1 connect=0ms service=3ms status=200 bytes=117 protocol=https
2024-05-17T21:01:26.870064+00:00 app[web.1]: file:///app/src/lib/utils.js:19
2024-05-17T21:01:26.870093+00:00 app[web.1]: const date = new Date().toLocaleString("en-US", { timeZone: tz });
2024-05-17T21:01:26.870094+00:00 app[web.1]: ^
2024-05-17T21:01:26.870094+00:00 app[web.1]: 
2024-05-17T21:01:26.870095+00:00 app[web.1]: RangeError: Invalid time zone specified: null
2024-05-17T21:01:26.870095+00:00 app[web.1]: at Date.toLocaleString (<anonymous>)
2024-05-17T21:01:26.870096+00:00 app[web.1]: at getNow (file:///app/src/lib/utils.js:19:27)
2024-05-17T21:01:26.870096+00:00 app[web.1]: at file:///app/src/routes/streakResetter.js:122:26
2024-05-17T21:01:26.870097+00:00 app[web.1]: at runNextTicks (node:internal/process/task_queues:60:5)
2024-05-17T21:01:26.870097+00:00 app[web.1]: at listOnTimeout (node:internal/timers:538:9)
2024-05-17T21:01:26.870097+00:00 app[web.1]: at process.processTimers (node:internal/timers:512:7)
2024-05-17T21:01:26.870100+00:00 app[web.1]: 
2024-05-17T21:01:26.870101+00:00 app[web.1]: Node.js v18.19.1
2024-05-17T21:01:26.890874+00:00 app[web.1]: npm notice
2024-05-17T21:01:26.890971+00:00 app[web.1]: npm notice New minor version of npm available! 10.2.4 -> 10.8.0
2024-05-17T21:01:26.893488+00:00 app[web.1]: npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.0>
2024-05-17T21:01:26.893490+00:00 app[web.1]: npm notice Run `npm install -g npm@10.8.0` to update!
2024-05-17T21:01:26.893490+00:00 app[web.1]: npm notice
2024-05-17T21:01:26.972362+00:00 heroku[web.1]: Process exited with status 1
2024-05-17T21:01:26.995933+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by JosiasAurel** [comment]
Some users may apparently not have a timezone set on their scrapbook accounts
